Create ManageServerCard component
AnswerOverflow/AnswerOverflow pull request #178
Opened 2023-02-17 23:01 UTC by mwgiannini

#147

2023-02-17 23:05 UTC, JoltCode commented
Could we keep this open until the new design system pr is merged? Otherwise we'll have to open a new issue/pr to make this work with the new design system anyway @RhysSullivan

2023-02-17 23:12 UTC, RhysSullivan commented
Yeah that makes sense @JoltCode - @mwgiannini nice work on this PR I did a quick skim of the code and it looks pretty solid

2023-02-17 23:13 UTC, JoltCode commented
Yep - nice work!

2023-02-17 23:14 UTC, JoltCode commented
Depends on #146

2023-02-19 09:02 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/AnswerOverflow/AnswerOverflow?pullRequest=178) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/AnswerOverflow/AnswerOverflow?pullRequest=178) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/AnswerOverflow/AnswerOverflow?pullRequest=178) it.</sub>

2023-02-20 17:43 UTC, JoltCode requested changes
Really great work (had a proper look), just now needs a little update with the merge of #146 👍

2023-02-20 17:43 UTC, JoltCode commented on packages/ui/src/components/ManageServerCard.tsx
> +            <Button intent={"primary"} visualOnly>
This now needs to be updated to the new button (path should be the same, just different props and different styles

2023-02-20 17:44 UTC, JoltCode commented
Closes #147

2023-02-20 21:01 UTC, mwgiannini commented
Sounds good, thanks Jolt

2023-02-20 21:19 UTC, JoltCode commented
👍

2023-02-25 15:22 UTC, mwgiannini commented
@JoltCode @RhysSullivan This should be ready to merge.

2023-02-25 15:31 UTC, JoltCode approved these changes
LGTM

2023-02-25 15:31 UTC, JoltCode commented on packages/ui/src/components/ManageServerCard.tsx
> +          <Link href={`https://discord.gg/`} target={"Blank"} referrerPolicy="no-referrer">
Will open an issue for this - we shouldn't have buttons inside links (needs a component change for button)

2023-02-25 19:58 UTC, merged