feat(docs): noindex on staging deployment
AnswerOverflow/AnswerOverflow pull request #266
Opened 2023-03-13 17:38 UTC by JoltCode

# Description

Search engines should no longer index the staging version if a `STAGING = "1"` env variable is present.

Fixes #240 (issue)

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [x] This change requires a documentation update

# How Has This Been Tested?

N/A

# Checklist:

- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] I have added tests that prove my fix is effective or that my feature works 
- [ ] I have updated .env.example if I added a new environment variable
- [x] My PR title follows the [semantic commits](https://www.conventionalcommits.org/en/v1.0.0/) style

2023-03-13 17:39 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/AnswerOverflow/AnswerOverflow?pullRequest=266) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/AnswerOverflow/AnswerOverflow?pullRequest=266) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/AnswerOverflow/AnswerOverflow?pullRequest=266) it.</sub>

2023-03-13 18:18 UTC, JoltCode commented
Sure! 😄

2023-03-14 09:55 UTC, JoltCode commented
Ready for review 😄

2023-03-14 22:11 UTC, RhysSullivan requested changes
good start, went over needed changes w/ you on call

2023-03-14 22:11 UTC, RhysSullivan commented on .env.example
> +# STAGING = "1"
change from stagining 1 to DEPOYMENT_ENV, options are development, staging, production

2023-03-15 03:48 UTC, merged